---
- name: Set up post-login banner
  hosts: localhost  # You can specify a group or individual hosts here
  become: true  # Elevate privileges to root for writing to system files

  tasks:
    - name: Ensure the banner is displayed in /etc/motd
      copy:
        content: |
             *******************************
              *                             *
              * This system is managed by   *
              * Ansible                     *
              *                             *
              *******************************
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
        force: yes  # Overwrites the file if it exists

    - name: Ensure the banner is displayed in /etc/issue (for some Linux distros)
      copy:
        content: |
          *******************************
              *                             *
              * This system is managed by   *
              * Ansible                     *
              *                             *
              *******************************
        dest: /etc/issue
        owner: root
        group: root
        mode: '0644'
        force: yes  # Overwrites the file if it exists
